[build]
  publish = "."

[[redirects]]
  from = "/blog"
  to = "/blog/index.html"
  status = 200

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/videos"
  to = "/videos/index.html"
  status = 200
